//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace eLearnDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class CoursesTaken
    {
        public Nullable<int> CourseID { get; set; }
        public Nullable<int> LearnerID { get; set; }
        public int ID { get; set; }
    
        public virtual Courses Courses { get; set; }
        public virtual Learner Learner { get; set; }
    }
}
